# CLI Tools
brew "tree" # Print folder layout
brew "tmux" # Terminal multiplexer
brew "tpm" # Tmux plugin manager
brew "fish" # Fish Shell
brew "fisher" # Plugin manager for the Fish shell
brew "neovim" # Neovim text editor
brew "macchina" # System Information like neofetch
brew "ffmpeg" # Video and audio processing
brew "graphviz" # Required for Flamegraph etc using pprof

# Neovim Setup
brew "luarocks" # Required for rest.nvim
brew "wget" # Required for neovim mason.nvim
brew "pngpaste" # Required for neovim clipboard

# Standard Apps
cask "ghostty" # Terminal Emulator
cask "google-chrome" # Web Browser
cask "docker" # Containerisation Platform
cask "maccy" # Clipboard Manager
cask "dbngin" # Database GUI
cask "bruno" # API Client
cask "visual-studio-code" # Code Editor

# Window Management
tap "nikitabobko/tap" # Tap for aerospace
tap "FelixKratz/formulae" # Tap for borders
cask "aerospace" # Window Manager
brew "felixkratz/formulae/borders" # Window Highlighting

if ENV['HOMEBREW_WORK_APPS'] == "true"
  cask "microsoft-edge"
  cask "microsoft-teams"
end

if ENV['HOMEBREW_HOME_APPS'] == "true"
  # Taps
  tap "microsoft/mssql-release"

  # Database Drivers
  brew "mssql-tools18"
  brew "msodbcsql18"

  cask "tableplus"
  cask "google-drive"
  brew "mas" # Mac store manager

  # Mac App Store Apps
  mas "DaisyDisk", id: 411643860
  mas "Final Cut Pro", id: 424389933
end
