# System packages — macOS (brew)
[bootstrap.packages]
"brew:bash" = "latest"
"brew:git" = "latest"
"brew:tree" = "latest"
"brew:tmux" = "latest"
"brew:tpm" = "latest"
"brew:fish" = "latest"
"brew:fisher" = "latest"
"brew:neovim" = "latest"
"brew:fastfetch" = "latest"
"brew:graphviz" = "latest"
"brew:lazygit" = "latest"
"brew:hf" = "latest"
"brew:llama.cpp" = "latest"
"brew:jq" = "latest"
"brew:yq" = "latest"
"brew:gh" = "latest"
"brew:gitleaks" = "latest"
"brew:zoxide" = "latest"
"brew:fzf" = "latest"
"brew:fd" = "latest"
"brew:ripgrep" = "latest"
"brew:worktrunk" = "latest"
"brew:make" = "latest"
"brew:btop" = "latest"
"brew:nmap" = "latest"
"brew:tokei" = "latest"
"brew:caddy" = "latest"
"brew:duckdb" = "latest"
"brew:yt-dlp" = "latest"
"brew:p7zip" = "latest"
"brew:kubernetes-cli" = "latest"
"brew:shellcheck" = "latest"
"brew:automake" = "latest"
"brew:cmake" = "latest"
"brew:gcc" = "latest"
"brew:pkgconf" = "latest"
"brew:protobuf" = "latest"
"brew:luarocks" = "latest"
"brew:stylua" = "latest"
"brew:wget" = "latest"
"brew:pngpaste" = "latest"
"brew:coreutils" = "latest"
"brew:ffmpeg" = "latest"
"brew:imagemagick" = "latest"
"brew:resvg" = "latest"
"brew:tlrc" = "latest"
"brew:podman" = "latest"
"brew:podman-compose" = "latest"

[bootstrap.user]
login_shell = "/opt/homebrew/bin/fish"
